from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG KAMU 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SELAMANYA 💕")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MY BABY")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("SAYANG KAMU💞")


@register(outgoing=True, pattern='^.dino(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`DIN DINNN.....`")
    sleep(1)
    await typew.edit("`DINOOOOSAURUSSSSS!!`")
    sleep(1)
    await typew.edit("`🏃                        🦖`")
    await typew.edit("`🏃                       🦖`")
    await typew.edit("`🏃                      🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃   `LARII`          🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃WOARGH!   🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                    🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃  Huh-Huh           🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃          🦖`")
    await typew.edit("`🏃         🦖`")
    await typew.edit("`DIA SEMAKIN MENDEKAT!!!`")
    sleep(1)
    await typew.edit("`🏃       🦖`")
    await typew.edit("`🏃      🦖`")
    await typew.edit("`🏃     🦖`")
    await typew.edit("`🏃    🦖`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🦖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`PERNAAHHHHH KAHHH KAUUU MENGIRA`")
        await e.edit("`SEPEEERTIIIII APAAAA BENTUKKKKKKK CINTAAAA`")
        await e.edit("`RAMBUUUT WARNAAA WARNII`")
        await e.edit("`BAGAI GULALI`")
        await e.edit("`IMUUUTTTTT LUCUUU`")
        await e.edit("`WALAAUUUU TAK TERLALU TINGGI`")
        await e.edit("`GW GABUUTTTT`")
        await e.edit("`EMMMM BACOTNYA`")
        await e.edit("`GABUTTTT WOI GABUT`")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("`CILUUUKKK BAAAAA`")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🚶                                 🐢")
        await e.edit("`AHHH MANTAP`")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("😂")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`GABUT`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Terkadang`")
    sleep(1)
    await typew.edit("`Mencintai Seseorang`")
    sleep(1)
    await typew.edit("`Hanya Akan Membuang Waktumu`")
    sleep(1)
    await typew.edit("`Ketika Waktumu Habis`")
    sleep(1)
    await typew.edit("`Tambah Aja 5000`")
    sleep(1)
    await typew.edit("`Bercanda`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`mf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting Ke Server Cinta`",
            "`Mencari Target Cinta`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim Padamu, Dan Sekarang Aku Sangat Mencintai Mu, I Love You 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai, I LOVE YOU 💞`")
    sleep(1)
    await typew.edit("`I LOVE YOU SO MUCH!`")
    sleep(1)
    await typew.edit("`I NEED YOU!`")
    sleep(1)
    await typew.edit("`I WANT TO BE YOUR BOYFRIEND!`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💕💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💗💞`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💝💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💟💖`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💘💓`")
    sleep(1)
    await typew.edit("`Tapi Bo'ong`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.halo(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(3)
    await typew.edit("`hai kamu`")
    sleep(3)
    await typew.edit("`salken ya`")
    sleep(1)
    await typew.edit("`xixixixi`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.ldr(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Kasihan`")
    sleep(1)
    await typew.edit("`Cantik Cantik Kok`")
    sleep(1)
    await typew.edit("`Pacaran`")
    sleep(1)
    await typew.edit("`Online`")
    sleep(1)
    await typew.edit("`Aoakaowkowkw`")
    sleep(1)
    await typew.edit("`Canda Online`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.g(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(3)
    await typew.edit("`ganteng doang`")
    sleep(3)
    await typew.edit("`Tukang Ghosting`")
    sleep(1)
    await typew.edit("`Canda Setan:v`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.kasihan$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("yahhahah")
        await e.edit("kasian")
        await e.edit("jadi")
        await e.edit("bahan")
        await e.edit("gabut")
        await e.edit("dia")
        await e.edit("xixixixi")
        await e.edit("mana masih muda")
        await e.edit("Aoakaowkowkw")
        await e.edit("kasihan")
        await e.edit("udah")
        await e.edit("virtual")
        await e.edit("masih")
        await e.edit("berharap")
        await e.edit("dia serius:v")
        await e.edit("padahal")
        await e.edit("cuma")
        await e.edit("tempat gabut")
        await e.edit("xixixix")
        await e.edit("<TAMAT>")
 

@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`yahhahah`")
    sleep(1)
    await typew.edit("`kasian`")
    sleep(1)
    await typew.edit("`jadi`")
    sleep(1)
    await typew.edit("`bahan`")
    sleep(1)
    await typew.edit("`gabut`")
    sleep(1)
    await typew.edit("`dia`")
    sleep(1)
    await typew.edit("`xixixixi`")
    sleep(1)
    await typew.edit("`mana masih muda`")
    sleep(1)
    await typew.edit("`Aoakaowkowkw`")
    sleep(1)
    await typew.edit("`kasihan`")
    sleep(1)
    await typew.edit("`udah`")
    sleep(1)
    await typew.edit("`virtual`")
    sleep(1)
    await typew.edit("`masih`")
    sleep(1)
    await typew.edit("`berharap`")
    sleep(1)
    await typew.edit("`dia serius:v`")
    sleep(1)
    await typew.edit("`padahal`")
    sleep(1)
    await typew.edit("`cuma`")
    sleep(1)
    await typew.edit("`tempat gabut`")
    sleep(1)
    await typew.edit("`xixixix`")
    sleep(1)
    await typew.edit("`TAMAT`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "`.gabut` ; `.dino`\
    \nUsage: ntahlah gabut doang.\
    \n\n`.gombal`\
    \nUsage: buat bercanda\
    \n\n`.halo`\
    \nUsage: untuk kenalan.\
    \n\n`.ldr`\
    \nUsage: pacaran onlen.\
    \n\n`.g`\
    \nUsage: ghosting.\
    \n\n`.kasihan`\
    \nUsage: mengsedih.\
    \n\n`.cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`.sayang`\
    \nUsage: untuk jadi buaya.\
    \n\n`.terkadang`\
    \nUsage: Auk dah iseng doang."
})
